rename bookstack to analyticsstack
DOME-Marketplace/dome-gitops pull request #353
Opened 2024-07-25 08:34 UTC by peppasnet

2024-07-25 12:56 UTC, nitto75 approved these changes

2024-07-25 13:32 UTC, nitto75 requested changes
Please Add SBX prefix into PR name and squash the commits.

2024-07-26 06:31 UTC, peppasnet commented
I did the REBASE (as Daniele suggested) but the squash option is not enabled for me. It gives me only two options (merge or rebase).

2024-07-26 07:34 UTC, nitto75 approved these changes

2024-07-26 07:34 UTC, merged