Prd add issuer componenet
DOME-Marketplace/dome-gitops pull request #401
Opened 2024-09-03 13:13 UTC by rubenmodamioin2

Prd add issuer componenet

2024-09-06 10:04 UTC, bialask-daiteap requested changes

2024-09-06 11:19 UTC, rubenmodamioin2 commented on ionos_prd/issuer/templates/dome-issuer-keycloak-admin-sealed-secret.yaml
> +    password: AgDDZqo/Uh1hkpYTggeGXeEWbrDu85ld1OrBBF97HkeFB0rDplNMvSLJGVinS6aMTjq9EFcKLxPIvrhfrc88rRfo9KxVSa7A3q6mrskHBCbuPM0kYjnuNA4bT/907bIuPHgY4OdbmKsdkzYi/JOf1uQHs7/A9cOGYnkGW/t+tcfkCSoeCXTl7ISnw
It's fine to put all the secrets in one file, but there's one thing I'd like to discuss regarding this: in the dev PR, which is linked here https://github.com/DOME-Marketplace/dome-gitops/pull/314 , as you can see, both in dev and SBX they are in several files. If it seems good to you, I can create a PR to group them into a single file starting with SBX and then proceeding to dev2.

2024-09-06 12:20 UTC, bialask-daiteap commented on ionos_prd/issuer/templates/dome-issuer-keycloak-admin-sealed-secret.yaml
> +    password: AgDDZqo/Uh1hkpYTggeGXeEWbrDu85ld1OrBBF97HkeFB0rDplNMvSLJGVinS6aMTjq9EFcKLxPIvrhfrc88rRfo9KxVSa7A3q6mrskHBCbuPM0kYjnuNA4bT/907bIuPHgY4OdbmKsdkzYi/JOf1uQHs7/A9cOGYnkGW/t+tcfkCSoeCXTl7ISnw
ok let's keep consistency. But for the future please keep them in one file / resource if any changes are planned

2024-09-06 12:43 UTC, rubenmodamioin2 commented on ionos_prd/issuer/templates/dome-issuer-keycloak-admin-sealed-secret.yaml
> +    password: AgDDZqo/Uh1hkpYTggeGXeEWbrDu85ld1OrBBF97HkeFB0rDplNMvSLJGVinS6aMTjq9EFcKLxPIvrhfrc88rRfo9KxVSa7A3q6mrskHBCbuPM0kYjnuNA4bT/907bIuPHgY4OdbmKsdkzYi/JOf1uQHs7/A9cOGYnkGW/t+tcfkCSoeCXTl7ISnw
Okay ill start with SBX

2024-09-06 13:31 UTC, rubenmodamioin2 commented on ionos_prd/issuer/templates/dome-issuer-keycloak-admin-sealed-secret.yaml
> +    password: AgDDZqo/Uh1hkpYTggeGXeEWbrDu85ld1OrBBF97HkeFB0rDplNMvSLJGVinS6aMTjq9EFcKLxPIvrhfrc88rRfo9KxVSa7A3q6mrskHBCbuPM0kYjnuNA4bT/907bIuPHgY4OdbmKsdkzYi/JOf1uQHs7/A9cOGYnkGW/t+tcfkCSoeCXTl7ISnw
I've created the PR on SBX: https://github.com/DOME-Marketplace/dome-gitops/pull/405

2024-09-06 13:32 UTC, rubenmodamioin2 commented on ionos_prd/issuer/templates/dome-issuer-keycloak-admin-sealed-secret.yaml
> +    password: AgDDZqo/Uh1hkpYTggeGXeEWbrDu85ld1OrBBF97HkeFB0rDplNMvSLJGVinS6aMTjq9EFcKLxPIvrhfrc88rRfo9KxVSa7A3q6mrskHBCbuPM0kYjnuNA4bT/907bIuPHgY4OdbmKsdkzYi/JOf1uQHs7/A9cOGYnkGW/t+tcfkCSoeCXTl7ISnw
I've created the [PR](I've created the PR on SBX: https://github.com/DOME-Marketplace/dome-gitops/pull/405l) on SBX

2024-09-12 11:27 UTC, rubenmodamioin2 commented on applications_prd/release1/in2/issuer.yaml
> +metadata:
https://github.com/DOME-Marketplace/dome-gitops/pull/314

2024-09-12 11:46 UTC, bialask-daiteap commented on applications_prd/release1/in2/issuer.yaml
> +metadata:
Ok thank you

2024-09-12 11:47 UTC, bialask-daiteap commented
The MR is fine. Please move the application from /release1 to /release2 folder

2024-09-12 12:03 UTC, rubenmodamioin2 commented
I created the release2 folder and now the issuer is inside the release 2 folder

2024-09-12 12:36 UTC, merged