SBX - cleanup default values to get up-to-date with the access-node c…
DOME-Marketplace/dome-gitops pull request #467
Opened 2024-10-09 12:33 UTC by wistefan

The values file contained the default values of the access-node chart. Due to that, updates to the access-node components do not have an effect. 
https://github.com/DOME-Marketplace/dome-gitops/pull/457 did not increase the TMForum version due to that. 

In order to follow best practices of using helm and have an actual tested access-node deployed, the defaults have to be removed again.

2024-10-09 15:05 UTC, bialask-daiteap requested changes

2024-10-09 15:05 UTC, bialask-daiteap commented on ionos_sbx/marketplace/access-node/values.yaml
> -      image:
Please rebase the changes

2024-10-10 09:00 UTC, wistefan commented on ionos_sbx/marketplace/access-node/values.yaml
> -      image:
done

2024-10-10 09:41 UTC, bialask-daiteap approved these changes

2024-10-10 09:41 UTC, merged