SBX-Certification-backend add sealedsecrets and ConfigMap
DOME-Marketplace/dome-gitops pull request #546
Opened 2024-11-11 18:02 UTC by intentodepirata

I have created the ConfigMap for the SBX environment for the Certification Backend and also the Sealed Secret. However, I'm not sure how to proceed with encrypting the secrets. Should I pass them over and let the DevOps team encrypt them, or is there a specific process I need to follow?

I have created the Merge Request (MR) with these changes.

Best regards,

2024-11-13 16:29 UTC, intentodepirata commented
Recently I sealed the secrets via kubeseal i commit in SBX/dome-certification/backend/templates/certification-backend-sealed-secret.yaml

2024-11-14 07:55 UTC, bialask-daiteap requested changes

2024-11-14 07:55 UTC, bialask-daiteap commented on ionos_sbx/dome-certification/backend/certification-backend-config.yaml
> +  name: certification-backend-config
Please squash the commits.

2024-11-14 09:01 UTC, intentodepirata commented
I just brought the changes from main to have the branch updated, now I don't know how to do the squash

2024-11-14 11:53 UTC, bialask-daiteap approved these changes

2024-11-14 11:53 UTC, merged