fix tm-forum api
DOME-Marketplace/dome-gitops pull request #97
Opened 2024-06-10 13:00 UTC by dleonardi95

Some configs was missing, those changes should solve the deploy for the tmforum in both Dev and Sbx enviroment

2024-06-10 14:08 UTC, fdelavega commented on ionos_dev/marketplace/tmforum-api/values.yaml
> +      specUrl: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/4.0.0/swagger/TMF632-Party-v4.0.0.swagger.json
Is the specUrl still used? the swagger file is now part of the TMForum API project

2024-06-11 06:17 UTC, wistefan commented
This is just the documentation of the apis that was deployed for demo. There is no point in deploying it here.

2024-06-13 15:02 UTC, bialask-daiteap commented
Please explain why in one file with application there is reference to to resources for one environment while in the same MR the resources are defined for different environment.
If we modify something, let's split the MRs one per environment.
Adding resources to the folder not referenced in applications_dev folder should not take place.
![image](https://github.com/DOME-Marketplace/dome-gitops/assets/155756826/8a906b96-736d-43bd-ae06-719dd1f4b192)

2024-06-14 06:11 UTC, wistefan commented
@bialask-daiteap I dont understand you question. But still, this is nothing that should be deployed anywhere else then demo and it will be replaced by the access-node chart anyways. I would recommend to delete that PR.

2024-06-14 06:57 UTC, bialask-daiteap requested changes
Please split MR one per env

2024-06-14 07:20 UTC, closed without merging